
nouns1 = {
"vuosi ": "year",
"markka ": "mark (old currency)",
"maa ": "country, land",
"asia ": "thing, matter",
"prosentti ": "percent",
"ihminen ": "person, human being",
"mies ": "husband, man",
"aika ": "time",
"työ ": "work",
"mieli ": "mind",
"kaupunki ": "city",
"osa ": "part, section, component",
"alue ": "area, region",
"lapsi ": "child",
"päivä ": "day",
"hallitus ": "government, board, regime",
"kunta ": "municipality",
"nainen ": "woman",
"viikko ": "week",
"luku ": "number, count, quantity",
"kerta ": "time",
"yritys ": "company, enterprise, firm",
"alku ": "beginning, start",
"paikka ": "place",
"tilanne ": "situation",
"presidentti ": "president",
"tieto ": "knowledge, information",
"loppu ": "end",
"tapa ": "way, custom, habit",
"maailma ": "the world",
"määrä ": "amount",
"puheenjohtaja ": "chairman, president",
"poliisi ": "police, policeman",
"kisa ": "race, competition",
"auto ": "car",
"toiminta ": "activity, action",
"tulos ": "result",
"raha ": "money",
"päätös ": "decision",
"käyttö ": "use",
"syy ": "cause, reason, source",
"elämä ": "life",
"kilpailu ": "competition",
"koulu ": "school",
"kesä ": "summer",
"ongelma ": "problem",
"yhtiö ": "company, corporation, partnership",
"joukkue ": "team",
"nuori ": "jong",
"mahdollisuus ": "possibility",
"kausi ": "season",
"suomalainen ": "Finn",
"valtio ": "state",
"kuva ": "picture",
"nimi ": "name",
"joukko ": "a troop",
"johtaja ": "manager",
"tila ": "space, area",
"apu ": "help, assistance",
"ryhmä ": "group",
"hetki ": "moment",
"tehtävä ": "task",
"puolue ": "party (political)",
"tavoite ": "goal",
"voitto ": "profit, gains, return",
"matka ": "trip",
"kauppa ": "shop",
"ottelu ": "match, game",
"sopimus ": "agreement, contract, bargain",
"maanantai ": "Monday",
"hinta ": "price",
"sunnuntai ": "Sunday",
"sarja ": "series",
"perjantai ": "Friday",
"puoli ": "half",
"lauantai ": "Saturday",
"yhteistyö ": "co-operation",
"jäsen ": "limb",
"tutkimus ": "research",
"syksy ": "autumn (UK); fall (USA)",
"torstai ": "Thursday",
"tiistai ": "Tuesday",
"keskiviikko ": "Wednesday",
"kysymys ": "question",
"talo ": "house",
"kuukausi ": "month",
"ohjelma ": "program",
"ratkaisu ": "solution",
"peli ": "game, match",
"kirja ": "book",
"tuki ": "assistant, support",
"poika ": "boy",
"esitys ": "performance",
"edustaja ": "representative",
"ala ": "field",
"tie ": "road",
"perhe ": "family",
"metri ": "meter",
"oikeus ": "rightness, justice",
"asema ": "station",
"elokuva ": "movie",
"voima ": "power",
"tarkoitus ": "idea, intention",
"johto ": "management, administration",
"muutos ": "change",
"tunti ": "hour, lesson",
"tapahtuma ": "happening",
"hanke ": "undertaking, enterprise",
"kevät ": "spring",
"piste ": "dot, end, period",
"kokous ": "meeting",
"vesi ": "water",
"liitto ": "alliance",
"tulevaisuus ": "future",
"ääni ": "sound, voice, vote",
"palvelu ": "service",
"juttu ": "story, tale",
"kunto ": "condition, fitness",
"taso ": "level, plane",
"pääministeri ": "prime minister",
"tulo ": "coming, arrival",
"keskusta ": "center, city center",
"työntekijä ": "employee",
"osuus ": "share",
"käsi ": "hand",
"lehti ": "leaf",
"asiakas ": "client, customer",
"henkilö ": "person",
"sivu ": "page",
"klo ": "clock (abbrevation of kello)",
"raja ": "boundary",
"toimitusjohtaja ": "managing director, chief executive officer (CEO)",
"musiikki ": "music",
"teos ": "piece of work",
"kasvu ": "growth",
"talous ": "economy",
"sota ": "war",
"koti ": "home",
"kilometri ": "kilometer",
"asukas ": "inhabitant",
"käytäntö ": "practice, custom",
"vaali ": "election",
"kirkko ": "church",
"minuutti ": "minute",
"keskustelu ": "discussion",
"tapaus ": "case, incident",
"eduskunta ": "Parliament",
"ero ": "difference, distinction",
"arvo ": "value",
"henki ": "spirit, life, soul",
"neuvottelu ": "conference, council",
"seura ": "association",
"vaihe ": "stage",
"pankki ": "bank",
"koulutus ": "education",
"miljoona ": "one million",
"työpaikka ": "workplace",
"rakentaminen ": "building",
"suhde ": "ratio, proportion",
"historia ": "history",
"komissio ": "commission",
"laki ": "law",
"pelaaja ": "player",
"kello ": "clock; watch; bell",
"näyttely ": "show, exhibition, display",
"yhteys ": "connection",
"kokemus ": "experience, knowledge",
"ehdokas ": "candidate, nominee",
"asunto ": "residence",
"kehitys ": "utveckling",
"osake ": "a share (of stock)",
"huomio ": "attention",
"äiti ": "mother",
"yleisö ": "public, audience",
"myynti ": "sales",
"hoito ": "treatment, care",
"tarve ": "need",
"suunta ": "direction",
"lupa ": "permission, license",
"ajatus ": "thought",
"tyttö ": "girl",
"kohde ": "a target",
"tuote ": "product",
"kone ": "machine",
"opettaja ": "teacher",
"ilta ": "evening",
"maakunta ": "province",
"markkinat ": "market",
"kieli ": "tongue, language",
"vuosikymmen ": "decade",
"tekijä ": "factor",
"kansa ": "people",
"yö ": "night",
"sana ": "word",
"vaihtoehto ": "option",
"merkitys ": "significance",
"isä ": "father",
"liike ": "shop",
"suunnitelma ": "plan",
"tuotanto ": "works (the body of an artists work)",
"valmentaja ": "coach, trainer",
"malli ": "a model, pattern, design",
"parlamentti ": "parliament",
"kansalainen ": "citizen",
"pää ": "head",
"vanhempi ": "senior",
"aihe ": "topic",
"talvi ": "winter",
"vauhti ": "speed",
"yhteiskunta ": "society",
"meno ": "expenditure",
"vaikutus ": "influence",
"rakennus ": "building",
"kylä ": "village, town",
"kanta ": "stem, opinion, basis, position",
"opiskelija ": "student",
"metsä ": "forest",
"liikenne ": "traffic",
"tutkija ": "researcher, scientist",
"laji ": "species",
"vastuu ": "responsibility",
"kansanedustaja ": "congressman",
"rooli ": "role, part",
"järjestö ": "organization",
"puu ": "wood (material) / tree",
"etu ": "advantage",
"professori ": "professor",
"luokka ": "class",
"linja ": "line, route",
"elokuu ": "August",
"politiikka ": "policy, politics",
"seutu ": "region",
"oppilas ": "student",
"kierros ": "round",
"kesäkuu ": "June",
"piiri ": "circle",
"valinta ": "selection, choice",
"euro ": "euro",
"puhe ": "speech",
"kulttuuri ": "culture",
"ura ": "career",
"huoli ": "worry, concern",
"valtuusto ": "council",
"liiga ": "league",
"kokoomus ": "coalition",
"kehittäminen ": "development of, evolution",
"omistaja ": "owner",
"silmä ": "eye",
"projekti ": "project",
"yhdistys ": "association, society",
"nousu ": "rise, ascent",
"viranomainen ": "official, authority",
"kenttä ": "field",
"erä ": "entry, item, game",
"tarina ": "story",
"teatteri ": "theater",
"väki ": "people",
"tekeminen ": "making, conclusion",
"yrittäjä ": "entrepreneur",
"ministeri ": "minister",
"kustannus ": "cost",
"sairaala ": "hospital",
"syyskuu ": "September",
"merkki ": "sign",
"Keskus ": "The Center",
"lokakuu ": "October",
"sekunti ": "second (unity of time)",
"onni ": "luck",
"luonto ": "nature",
"valta ": "power",
"ympäristö ": "environment",
"pohja ": "base",
"toukokuu ": "May",
"keino ": "way",
"taiteilija ": "artist",
"tehdas ": "factory",
"toimittaja ": "journalist, reporter",
"maaliskuu ": "March",
"ruoka ": "food",
"heinäkuu ": "July",
"tammikuu ": "January",
"virka ": "post",
"kriisi ": "a crisis",
"vara ": "reserve, allowance",
"tausta ": "background",
"joulukuu ": "December",
"yliopisto ": "university",
"selvitys ": "statement",
"lääkäri ": "medical doctor, physician",
"dollari ": "dollar",
"sija ": "place, position",
"mestaruus ": "championship, title",
"marraskuu ": "November",
"tilaisuus ": "occasion",
"olo ": "condition",
"ystävä ": "friend",
"jalka ": "foot",
"palkinto ": "prize, award",
"konsertti ": "concert",
"rauha ": "peace",
"katsoja ": "spectator",
"pakolainen ": "refugee",
"ulkomaa ": "foreigners",
"palkka ": "reward, fee",
"juhla ": "party",
"levy ": "disc, record",
"järjestelmä ": "system",
"toimi ": "chore, job, duty, action",
"julkisuus ": "publicity",
"teko ": "act/deed",
"lasku ": "bill",
"kyse ": "matter, about",
"vieras ": "foreign",
"potilas ": "patient",
"ovi ": "door",
"budjetti ": "budget",
"laitos ": "facility",
"näytelmä ": "play (theatrical performance)",
"menestys ": "success",
"arvio ": "estimate, valuation",
"rata ": "track",
"kirjailija ": "author",
"voittaja ": "winner",
"kappale ": "chapter",
"turvallisuus ": "security, safety",
"lähtö ": "departure",
"räntä ": "sleet",
"televisio ": "television",
"ulkoministeri ": "foreign minister",
"esimerkki ": "example, paradigm",
"teksti ": "text",
"taistelu ": "fight",
"vaatimus ": "requirement",
"seurakunta ": "parish, congregation",
"kurssi ": "course",
"armeija ": "army",
"työryhmä ": "team, task force",
"vaikeus ": "difficulty",
"ehto ": "condition",
"taide ": "art",
"ehdotus ": "proposal",
"jälki ": "track, trace",
"katu ": "street",
"muoto ": "form, format",
"tappio ": "defeat, loss",
"jatko ": "continuation",
"näkemys ": "opinion, position, vision",
"mestari ": "master",
"teollisuus ": "industry",
"kilo ": "kilogram",
"käsittely ": "treatment",
"vaimo ": "wife",
"tunne ": "feeling",
"helmikuu ": "February",
"ote ": "extract",
"huhtikuu ": "April",
"uhri ": "a victim",
"idea ": "idea",
"rahoitus ": "financing",
"viikonloppu ": "weekends",
"liikevaihto ": "sales, revenue",
"kärki ": "point",
"laulu ": "song",
"eläke ": "pension",
"laatu ": "quality",
"koira ": "dog",
"vastaus ": "answer",
"seuraus ": "consequence",
"joulu ": "Christmas",
"työttömyys ": "unemployment",
"kotimaa ": "home country",
"väli ": "spacing",
"lista ": "list",
"valo ": "light",
"jakso ": "period, section",
"vuosituhat ": "millennium",
"venäläinen ": "Russian",
"lausunto ": "statement",
"kaupunginhallitus ": "municipality",
"virhe ": "error, mistake",
"asiantuntija ": "expert",
"kuljettaja ": "driver",
}
nouns2 = {
"muovi": "plastic",
"valikoima": "selection",
"ruokala": "canteen, cafeteria",
"ympäristö": "environment",
"pahvi": "cardboard",
"vihreä puolue": "green party",
"vuoden loppuun asti": "until beginning next year",
"uupumus": "exhaustion, fatigue",
"lepo": "rest",
"väkiluku": "population",
"arkisto": "archive",
"säädös": "statute, decree",
"tällä kertaa": "this time",
"verkkopalvelu": "online service",
"käyttäminen": "Benutzung",
"näkövamma": "visuak impairment",
"kielitaito": "language level",
"ohje": "indication, help, instruction",
"siitä": "thence",
"nettisivu": "webpage",
"konttori": "branch",
"tili": "account",
"tilin avaaminen": "Kontoeröffnung",
"tulkki": "translator",
"tilin ehdot": "bank account terms",
"elekieli": "body language",
"käytänne": "practice",
"käytännössä": "to practice",
"koulutus": "training, education",
"tausta": "background",
"maahanmuuttaja": "immigrant",
"asiakaskunta": "clientele",
"yhdenvertaisuus": "equality",
"esite": "brochure",
"kielivaikeus": "language difficulty",
"ohjelma": "program, show",
"sarja": "series",
"isku": "attack",
"synagooga": "synagogue",
"väkivalta": "violence, force",
"kuolemanrangaistus": "death penalty",
"joukkomurha": "massacre",
"viha": "hate",
"uskonto": "religion",
"mittaus": "measurement",
"kemikaaleja": "chemical",
"yhdiste": "compound, union",
"markkinajohtaja": "market leader",
"valmistaja, tuottaja": "manufacturer",
"eri maista": "aus verschiedenen Ländern",
"kuurankukka": "frost flower",
"kuura": "frost",
"lumikuuro": "snow shower, snow flurry",
"pakkasaste": "freezing conditions",
"piiri": "circle",
"taikausko": "superstition",
"viulu": "violin",
"vitsi": "joke",
"naurattaa": "to make laugh",
"eduskunta": "Parliament",
"korko": "interest rate",
"maanviljelijä": "farmer",
"ruis": "rye",
"velvollisuus": "duty",
"papukaija": "parrot",
"selitys": "explanation",
"filosofia": "philosophy",
"vakooja": "spy",
"tulo": "income",
"pelikonsoli": "game console",
"": "",
"agentti": "agent",
"strategiapeli": "strategy game",
"lemmikki": "pet",
"kilpailu": "competition",
"riita": "argument",
"ase": "gun, weapon",
"pelko": "fear",
"ensimmäinen maailmansota": "World War I",
"joku": "someone, somebody",
"lupa": "authorization, permit, permission",
"tietokoneohjelma": "software",
"liputuspäivä": "Flag Day",
"tanko": "bar, rail, pol",
"kuorma-autonkuljettaja": "truck driver",
"myyntiedustaja": "sales representative",
"rakennusmies": "construction worker",
"oikea vastaus": "right answer",
"joku Suomesta": "someone from Finland",
"harjoitus, harjoittelu": "Übung",
"päihde": "intoxicant, drug",
"ratkaisu": "solution",
"ammattilainen": "professional",
"vaikuttaja": "policy maker, opinion leader",
"muuttaminen": "changing, transformation",
"haaste": "challenge",
"helpotus": "relief",
"haitta": "disadvantage, downside, hindrance",
"rentoutus": "relaxation",
"tentti": "exam, test",
"muotokuva": "portrait",
"tupakka": "tobacco, cigarette",
"liikenne": "traffic, transport",
"vesipisara": "water drop",
"kohtelu": "treatment",
"kerho": "club, society",
"paraati": "parade",
"Viro": "Estonia",
"ahdistus": "anxiety",
"päällikkö": "chief, leader",
"turvapaikka": "asylum",
"syy on se, että": "grund dafür ist, dass...",
"opintotuki": "student allowance/benefit",
"tietoliikenne": "telecommunication",
"herkku": "delicacy",
"pysäkki": "tram/bus stop",
"hälytys": "alarm",
"tuhka": "ash",
"takka": "fireplace"
}
nouns3 = {
"glögi": "mulled wine",
"kuusi": "spruce",
"pulla": "bun",
"aamu": "morning",
"viikinki": "viking",
"sisu": "perseverance",
"ääni": "sound, voice",
"ahma": "wolverine",
"kala": "fish",
"sinappi": "mustard",
"mämmi": "finnish easter pudding",
"makkara": "sausage",
"tori": "market square",
"kahvila": "café",
"äiti": "mother",
"sauna": "sauna",
"kantele": "finnish plucked string instrument",
"hiihto": "cross-country skiing",
"jää": "ice",
"jääkiekko": "ice hockey",
"järvi": "lake",
"joki": "river",
"karaoke": "karaoke",
"karhu": "bear",
"karjalanpiirakka": "karelian pasty",
"karkki": "candy, sweets",
"kiisseli": "fruit pudding",
"kinuski": "russian candy",
"korvapuusti": "cinnamon bun",
"lakritsi": "licorice",
"lörtsy": "half-moon shaped pastry",
"lumi": "snow",
"marja": "berry",
"metro": "subway",
"munkki": "doughnut often filled with jelly",
"olut": "beer",
"pipo": "beanie",
"poro": "reindeer",
"saari": "island",
"salmiakki": "salty licorice",
"sima": "mead",
"suksi": "ski",
"takki": "coat",
"kahvi": "coffee",
"suomenkieli": "finnish language",
"akku": "battery",
"aksentti": "accent",
"ale": "sale",
"annos": "portion",
"appelsiini": "orange (fruit)",
"asukas": "resident, inhabitant",
"asunto": "apartment",
"aurinko": "sun",
"auto": "car",
"baletti": "ballet",
"banaani": "banana",
"bändi": "music band (slang)",
"biisi": "song (slang)",
"deodorantti": "deodorant",
"eläin": "animal",
"elokuva": "film, movie, motion picture",
"euro": "euro",
"eväät": "packed lunch, lunch",
"grilli": "grill",
"haarukka": "fork",
"hai": "shark",
"hamsteri": "hamster",
"hattu": "hat",
"helmi": "pearl",
"herkku": "treat, delicacy",
"hetki": "moment, instant",
"hevonen": "horse",
"hiiri": "mouse",
"hiki": "sweat",
"hillo": "jam",
"hirvi": "moose",
"historia": "history",
"hotelli": "hotel",
"housut": "pants, trousers",
"huone": "room",
"huuhkaja": "eagle owl",
"hymy": "smile",
"ihminen": "person",
"insinööri": "engineer",
"isä": "father, dad",
"jäätelö": "ice cream",
"jalkapallo": "soccer, football",
"juusto": "cheese",
"käärme": "snake",
"kalenteri": "calendar",
"kameli": "camel",
"kamera": "camera",
"kampa": "comb",
"kana": "chicken",
"kännykkä": "mobile phone, cellphone",
"kartta": "map",
"kastike": "sauce",
"kasvi": "plant",
"katto": "roof, ceiling",
"katu": "street",
"kaupunki": "city, town",
"keittiö": "kitchen",
"keitto": "soup",
"kellari": "cellar, basement",
"kemia": "chemistry",
"kengät": "shoes",
"kenguru": "kangaroo",
"kerma": "cream",
"ketsuppi": "ketchup",
"kieli": "language",
"kirkko": "church",
"kissa": "cat",
"kitara": "guitar",
"kivi": "stone, rock",
"koala": "koala",
"koira": "dog",
"kokki": "chef",
"koripallo": "basketball",
"koru": "jewelry",
"koti": "home",
"kravatti": "tie, necktie",
"krokotiili": "crocodile",
"kuoro": "choir",
"kuppi": "cup",
"kuu": "moon, month",
"kuulokkeet": "headphones",
"kysymys": "question",
"lääkkeet": "medicines, drugs",
"lamppu": "lamp",
"läppäri": "laptop",
"lapsi": "child, kid",
"lasi": "glass, glass cup",
"lasku": "bill, invoice",
"lattia": "floor",
"laturi": "charger",
"laulaja": "singer, vocalist",
"laulu": "song",
"lause": "sentence, clause",
"lautanen": "plate",
"lehti": "leaf, magazine",
"leijona": "lion",
"leipä": "bread",
"leivos": "pastry",
"lelu": "toy",
"lemmikki": "pet",
"liha": "meat",
"limonadi": "soda, lemonade",
"linna": "castle",
"lintu": "bird",
"lippu": "ticket, flag",
"loma": "holiday, vacation",
"lompakko": "wallet",
"lounas": "lunch",
"lusikka": "spoon",
"maa": "country, ground, soil",
"maalaus": "painting",
"maito": "milk",
"mäkeä": "hill",
"matkailu": "tourism",
"mauste": "spice, seasoning",
"meemi": "meme",
"mehu": "juice",
"mekko": "dress",
"meri": "sea, ocean",
"metsä": "forest",
"mies": "man",
"mikrofoni": "microphone",
"minuutti": "minute",
"monumentti": "monument",
"mummo": "grandmother",
"muotia": "fashion",
"murre": "dialect",
"museo": "museum",
"muusikko": "musician",
"nainen": "woman",
"nalle": "teddy bear",
"näytelmä": "play, show",
"netti": "net, internet",
"nimi": "name",
"omena": "apple",
"onnea": "luck",
"ooppera": "opera",
"oopperatalo": "opera house",
"opettaja": "teacher, instructor",
"orava": "squirrel",
"paikka": "place",
"paita": "shirt",
"pari": "couple",
"pasta": "pasta",
"peli": "game",
"pentu": "puppy, kitten",
"perhe": "family",
"peruna": "potato",
"perunasalaatti": "potato salad",
"pesäpallo": "baseball",
"piano": "piano",
"piha": "yard",
"pihvi": "steak",
"piirakka": "pie",
"pilvi": "cloud",
"pingviini": "penguin",
"pippuri": "pepper",
"pirtelö": "milkshake",
"pistoke": "plug",
"pitsa": "pizza",
"poika": "boy, son",
"pokeri": "poker",
"pöllö": "owl",
"poni": "pony",
"pöytä": "table",
"princessa": "princess",
"professori": "professor",
"puhelin": "telephone, phone",
"puisto": "park",
"pupu": "bunny",
"puro": "stream",
"puu": "tree",
"pyyhe": "towel",
"radio": "radio",
"raha": "money",
"rahka": "quark, curd",
"rakennus": "building",
"ralli": "rally",
"rauha": "peace",
"ravintola": "restaurant",
"riisi": "rice",
"ruoka": "food",
"ruuhka": "traffic",
"saippua": "soap",
"salaatti": "lettuce, salad",
"sana": "word",
"sandaalit": "sandals",
"sänky": "bed",
"sarja": "series",
"sauvat": "ski poles",
"sekunti": "second",
"sieni": "mushroom",
"siili": "hedgehog",
"sika": "pig",
"silta": "bridge",
"sipuli": "onion",
"sitruuna": "lemon",
"sohva": "sofa, couch",
"soitin": "instrument",
"sokeri": "sugar",
"sormus": "ring",
"sovellus": "app, application",
"sovituskoppi": "fitting room",
"stadion": "stadium",
"suklaa": "chocolate",
"sulhanen": "groom",
"suo": "swamp",
"suola": "salt",
"sushi": "sushi",
"susi": "wolf",
"sydän": "heart",
"tabletti": "tablet",
"tähti": "star",
"taivas": "sky",
"talo": "house",
"tammi": "oak",
"tango": "tango",
"tanssija": "dancer",
"tarjoilija": "waiter",
"taulu": "picture",
"täytekakku": "layer cake",
"teatteri": "theatre",
"tee": "tea",
"televisio": "television, tv",
"terassi": "terrace, patio",
"tie": "road",
"timantti": "diamond",
"tomaatti": "tomato",
"tulostin": "printer",
"turisti": "tourist",
"tyttö": "girl",
"tyttöystävä": "girlfriend",
"poikaystävä": "boyfriend",
"undulaatti": "parakeet",
"urheilu": "sport",
"vaari": "grandfather",
"vadelma": "raspberry",
"vaimo": "wife",
"väri": "color",
"varjo": "shade, shadow",
"vastaus": "response, answer",
"vauva": "baby",
"veitsi": "knife",
"velho": "wizard",
"veranta": "veranda",
"veri": "blood",
"vesi": "water",
"vesipullo": "water bottle",
"video": "video",
"viikko": "week",
"viini": "wine",
"virhe": "mistake, error",
"viulu": "violin",
"vyö": "belt",
"yliopisto": "university",
"yö": "night",
"päivä": "day",
"ilta": "evening",
"iltapäivä": "afternoon",
"ystävä": "friend"
}

for k, v in nouns2.items():
    if k not in nouns1.items():
        nouns1[k] = v

for kk, vv in nouns3.items():
    if kk not in nouns1.items():
        nouns1[kk] = vv

print(nouns1)

